export const RECOGNIZE_REQUESTED = 'RECOGNIZE_REQUESTED';
export const RECOGNIZE_SPEECH = 'RECOGNIZE_SPEECH';
export const RECOGNIZE_SUCCESS = 'RECOGNIZE_SUCCESS';
export const RECOGNIZE_ERROR = 'RECOGNIZE_ERROR';
export const RECOGNIZE_STOP = 'RECOGNIZE_STOP';

export const RESPONSE_OK = 'RESPONSE_OK';
export const INCOMPLETE_COMMAND = 'INCOMPLETE_COMMAND';
export const RESPONSE_ERROR = 'RESPONSE_ERROR';

export const NAME_CHANGED = 'NAME_CHANGED';
export const PIN_CHANGED = 'PIN_CHANGED';
export const SAVE_DEVICE = 'SAVE_DEVICE';
export const DELETE_DEVICE = 'DELETE_DEVICE';
export const SAVE_DEVICE_REQUEST = 'SAVE_DEVICE_REQUEST';
export const DEVICE_FILLED = 'DEVICE_FILLED';

export const GET_DEVICES_FAILED = 'GET_DEVICES_FAILED';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const CLEAR = 'CLEAR';

export const INPUT_CHANGED = 'INPUT_CHANGED';
export const KEYS_SAVED = 'KEYS_SAVED';
